workflows:
  my-workflow:
    instance_type: linux
    scripts:
      - name: Build Android App Bundle
        working_directory: android
        script: ./gradlew bundleRelease
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    scripts:
      - name: Build Android APK
        working_directory: android
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - dev.rignanese.leo@gmail.com
